<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container05JwjL5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container05JwjL5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container05JwjL5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container05JwjL5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container05JwjL5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '05JwjL5',
    'container.build_id' => '925723e2',
    'container.build_time' => 1553540791,
], __DIR__.\DIRECTORY_SEPARATOR.'Container05JwjL5');
