<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1zTvPow\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1zTvPow/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1zTvPow.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1zTvPow\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1zTvPow\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1zTvPow',
    'container.build_id' => '30f5ebf0',
    'container.build_time' => 1551295073,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1zTvPow');
