<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6CKzSCG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6CKzSCG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6CKzSCG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6CKzSCG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6CKzSCG\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6CKzSCG',
    'container.build_id' => 'c32d9106',
    'container.build_time' => 1553701592,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6CKzSCG');
